name: On Pull Request
on: pull_request
jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1
  lint:
    name: Run lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1
      - name: Run lint
        run: yarn lint
  unit-tests:
    name: Run unit tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
      - name: Install Node.js dependencies
        uses: bahmutov/npm-install@v1
      - name: Run unit tests
        run: yarn test
